apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: userservice
  namespace: boa
spec:
  hosts:
  - userservice
  http:
  - route:
    - destination:
        host: userservice
        subset: v1
      weight: 0
    - destination:
        host: userservice
        subset: v2
      weight: 100