apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: userservice
  namespace: boa
spec:
  host: userservice
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
