# Source: https://github.com/GoogleCloudPlatform/csp-config-management/blob/1.0.0/ci-pipeline/cloudbuild.yaml 
steps:
# Generate the kubeconfig file needed to authenticate to the GKE cluster. The root user generates this file with restricted permissions.
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['config', 'current-context']
  volumes:
  - name: 'kube'
    path: '/kube'
  env:
  - 'KUBECONFIG=/kube/config'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gcp'
  - 'CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true'
# Grant read permissions to the kubeconfig file.
- name: 'bash'
  args: ['chmod', '644', '/kube/config']
  volumes:
  - name: 'kube'
    path: '/kube'
# Grant read/write permissions to the workspace.
- name: 'bash'
  args: ['chmod', '777', '/workspace']
# Run nomos hydrate on the config-root directory and output the result into hydrated-configs.
- name: 'gcr.io/config-management-release/nomos'
  args: ['nomos', 'hydrate', '--path', '/workspace', '--output', '/workspace/hydrated-configs']
  volumes:
  - name: 'kube'
    path: '/kube'
  env:
  - 'KUBECONFIG=/kube/config'
# Recursively read a directory of kubernetes YAML configs from the workspace and output them as one list into config-source.yaml.
- name: 'gcr.io/config-management-release/read-yaml'
  args: ['--input', '/dev/null', '-d', 'source_dir=/workspace/hydrated-configs', '--output', '/workspace/config-source.yaml']
# Validate input configs against any OPA ConstraintTemplates and Constraints it finds in its input.
- name: 'gcr.io/config-management-release/policy-controller-validate'
  args: ['--input', '/workspace/config-source.yaml']
# Validate Istio API config 
- name: 'istio/istioctl:1.6.4'
  args: ['analyze', '/workspace/namespaces/', '--use-kube=false']