steps:
- name: 'bash'
  args: ['chmod', '777', '/workspace']
- name: 'gcr.io/config-management-release/nomos'
  args: ['nomos', 'vet', '--path', '/workspace']
- name: 'gcr.io/config-management-release/nomos'
  args: ['nomos', 'hydrate', '--path', '/workspace', '--output', '/workspace/configs']
- name: 'gcr.io/config-management-release/read-yaml'
  args: ['--input', '/dev/null', '-d', 'source_dir=/workspace/configs', '--output', '/workspace/config-source.yaml']
- name: 'gcr.io/config-management-release/policy-controller-validate'
  args: ['--input', '/workspace/config-source.yaml']
- name: 'istio/istioctl:1.6.4'
  args: ['analyze', '/workspace/namespaces/', '--use-kube=false']