apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PeerAuthnStrict
metadata:
  name: peer-authn-strict
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["security.istio.io"]
        kinds: ["PeerAuthentication"]
    namespaces: ["boa"]
